# Generated by Django 5.1.2 on 2024-10-26 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(13, message='ISBN must be exactly 13 characters')])),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('cover', models.URLField(blank=True, null=True)),
                ('language', models.CharField(db_comment='ISO 639-3 language code', max_length=3, validators=[django.core.validators.MinLengthValidator(3, message='ISO 639-3 language code must be exactly 3 characters.')])),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
    ]
